// -- init
// >= 2.0
XMACRO(PFNGLGETINTEGERVPROC, GetIntegerv)
XMACRO(PFNGLGETSTRINGPROC,   GetString)

#if defined(XMACRO_INIT)
	XMACRO_INIT()
	#undef XMACRO_INIT
#endif

// -- extensions
// >= 3.0
XMACRO(PFNGLGETSTRINGIPROC, GetStringi)

// -- settings
// >= 2.0
XMACRO(PFNGLDISABLEPROC, Disable)
XMACRO(PFNGLENABLEPROC,  Enable)
//
//    XMACRO(PFNGLDEPTHRANGEPROC, DepthRange)
// >= 4.1
XMACRO(PFNGLDEPTHRANGEFPROC, DepthRangef)
// >= 4.3
XMACRO(PFNGLDEBUGMESSAGECALLBACKPROC, DebugMessageCallback)
XMACRO(PFNGLDEBUGMESSAGECONTROLPROC,  DebugMessageControl)
// >= 4.5
XMACRO(PFNGLCLIPCONTROLPROC, ClipControl)

// -- color
// >= 2.0
XMACRO(PFNGLCLEARCOLORPROC,            ClearColor)
XMACRO(PFNGLCOLORMASKPROC,             ColorMask)
XMACRO(PFNGLBLENDCOLORPROC,            BlendColor)
//    XMACRO(PFNGLBLENDFUNCPROC,             BlendFunc)
//    XMACRO(PFNGLBLENDEQUATIONPROC,         BlendEquation)
XMACRO(PFNGLBLENDFUNCSEPARATEPROC,     BlendFuncSeparate)
XMACRO(PFNGLBLENDEQUATIONSEPARATEPROC, BlendEquationSeparate)

// -- depth
// >= 2.0
XMACRO(PFNGLDEPTHFUNCPROC,  DepthFunc)
XMACRO(PFNGLDEPTHMASKPROC,  DepthMask)
//    XMACRO(PFNGLCLEARDEPTHPROC, ClearDepth)
// >= 4.1
XMACRO(PFNGLCLEARDEPTHFPROC, ClearDepthf)

// -- stencil
// >= 2.0
//    XMACRO(PFNGLSTENCILMASKPROC,  StencilMask)
//    XMACRO(PFNGLSTENCILFUNCPROC,  StencilFunc)
//    XMACRO(PFNGLSTENCILOPPROC,    StencilOp)
//    XMACRO(PFNGLCLEARSTENCILPROC, ClearStencil)

// -- culling
// >= 2.0
XMACRO(PFNGLCULLFACEPROC,  CullFace)
XMACRO(PFNGLFRONTFACEPROC, FrontFace)

// -- GPU program
// >= 2.0
XMACRO(PFNGLATTACHSHADERPROC, AttachShader) // requires both 'program' and 'shader' ids
XMACRO(PFNGLDETACHSHADERPROC, DetachShader) // requires both 'program' and 'shader' ids
//
XMACRO(PFNGLCREATEPROGRAMPROC,     CreateProgram)
XMACRO(PFNGLDELETEPROGRAMPROC,     DeleteProgram)
XMACRO(PFNGLUSEPROGRAMPROC,        UseProgram)
XMACRO(PFNGLLINKPROGRAMPROC,       LinkProgram)
XMACRO(PFNGLGETPROGRAMIVPROC,      GetProgramiv)
XMACRO(PFNGLGETPROGRAMINFOLOGPROC, GetProgramInfoLog)
//    XMACRO(PFNGLGETPROGRAMBINARYPROC,  GetProgramBinary)
//
XMACRO(PFNGLCREATESHADERPROC,     CreateShader)
XMACRO(PFNGLDELETESHADERPROC,     DeleteShader)
XMACRO(PFNGLSHADERSOURCEPROC,     ShaderSource)
XMACRO(PFNGLCOMPILESHADERPROC,    CompileShader)
XMACRO(PFNGLGETSHADERIVPROC,      GetShaderiv)
XMACRO(PFNGLGETSHADERINFOLOGPROC, GetShaderInfoLog)
//    XMACRO(PFNGLGETSHADERSOURCEPROC,  GetShaderSource)
// >= 4.3
XMACRO(PFNGLGETPROGRAMINTERFACEIVPROC,  GetProgramInterfaceiv)
XMACRO(PFNGLGETPROGRAMRESOURCEIVPROC,   GetProgramResourceiv)
XMACRO(PFNGLGETPROGRAMRESOURCENAMEPROC, GetProgramResourceName)

// -- attributes (GPU program vertex locations)
// >= 2.0
//    XMACRO(PFNGLGETACTIVEATTRIBPROC,   GetActiveAttrib)
//    XMACRO(PFNGLGETATTRIBLOCATIONPROC, GetAttribLocation)

// -- uniforms (GPU program variables and constants)
// >= 2.0
//    XMACRO(PFNGLGETACTIVEUNIFORMPROC,   GetActiveUniform)
//    XMACRO(PFNGLGETUNIFORMLOCATIONPROC, GetUniformLocation)
// >= 3.1
//    XMACRO(PFNGLGETACTIVEUNIFORMSIVPROC, GetActiveUniformsiv)
//    XMACRO(PFNGLGETACTIVEUNIFORMNAMEPROC, GetActiveUniformName)
//
//    XMACRO(PFNGLUNIFORM1FVPROC, Uniform1fv)
//    XMACRO(PFNGLUNIFORM2FVPROC, Uniform2fv)
//    XMACRO(PFNGLUNIFORM3FVPROC, Uniform3fv)
//    XMACRO(PFNGLUNIFORM4FVPROC, Uniform4fv)
//
//    XMACRO(PFNGLUNIFORM1IVPROC, Uniform1iv) // also a sampler uniform
//    XMACRO(PFNGLUNIFORM2IVPROC, Uniform2iv)
//    XMACRO(PFNGLUNIFORM3IVPROC, Uniform3iv)
//    XMACRO(PFNGLUNIFORM4IVPROC, Uniform4iv)
//
//    XMACRO(PFNGLUNIFORMMATRIX2FVPROC, UniformMatrix2fv)
//    XMACRO(PFNGLUNIFORMMATRIX3FVPROC, UniformMatrix3fv)
//    XMACRO(PFNGLUNIFORMMATRIX4FVPROC, UniformMatrix4fv)
// >= 3.0
//    XMACRO(PFNGLUNIFORM1UIVPROC, Uniform1uiv)
//    XMACRO(PFNGLUNIFORM2UIVPROC, Uniform2uiv)
//    XMACRO(PFNGLUNIFORM3UIVPROC, Uniform3uiv)
//    XMACRO(PFNGLUNIFORM4UIVPROC, Uniform4uiv)
// >= 4.1
XMACRO(PFNGLPROGRAMUNIFORM1FVPROC, ProgramUniform1fv)
XMACRO(PFNGLPROGRAMUNIFORM2FVPROC, ProgramUniform2fv)
XMACRO(PFNGLPROGRAMUNIFORM3FVPROC, ProgramUniform3fv)
XMACRO(PFNGLPROGRAMUNIFORM4FVPROC, ProgramUniform4fv)
//
XMACRO(PFNGLPROGRAMUNIFORM1IVPROC, ProgramUniform1iv) // also a sampler uniform
XMACRO(PFNGLPROGRAMUNIFORM2IVPROC, ProgramUniform2iv)
XMACRO(PFNGLPROGRAMUNIFORM3IVPROC, ProgramUniform3iv)
XMACRO(PFNGLPROGRAMUNIFORM4IVPROC, ProgramUniform4iv)
//
XMACRO(PFNGLPROGRAMUNIFORM1UIVPROC, ProgramUniform1uiv)
XMACRO(PFNGLPROGRAMUNIFORM2UIVPROC, ProgramUniform2uiv)
XMACRO(PFNGLPROGRAMUNIFORM3UIVPROC, ProgramUniform3uiv)
XMACRO(PFNGLPROGRAMUNIFORM4UIVPROC, ProgramUniform4uiv)
//
XMACRO(PFNGLPROGRAMUNIFORMMATRIX2FVPROC, ProgramUniformMatrix2fv)
XMACRO(PFNGLPROGRAMUNIFORMMATRIX3FVPROC, ProgramUniformMatrix3fv)
XMACRO(PFNGLPROGRAMUNIFORMMATRIX4FVPROC, ProgramUniformMatrix4fv)

// -- textures
// >= 2.0
//    XMACRO(PFNGLGENTEXTURESPROC,    GenTextures)
XMACRO(PFNGLBINDTEXTUREPROC,    BindTexture)
XMACRO(PFNGLTEXIMAGE2DPROC,     TexImage2D)
//    XMACRO(PFNGLTEXPARAMETERIPROC,  TexParameteri)
XMACRO(PFNGLDELETETEXTURESPROC, DeleteTextures)
//    XMACRO(PFNGLTEXSUBIMAGE2DPROC,  TexSubImage2D)
// >= 4.2
//    XMACRO(PFNGLTEXSTORAGE2DPROC, TexStorage2D)
// >= 4.5
XMACRO(PFNGLCREATETEXTURESPROC,     CreateTextures)
XMACRO(PFNGLTEXTURESTORAGE2DPROC,   TextureStorage2D)
XMACRO(PFNGLTEXTUREPARAMETERIPROC,  TextureParameteri)
XMACRO(PFNGLTEXTUREPARAMETERIVPROC, TextureParameteriv)
XMACRO(PFNGLTEXTURESUBIMAGE2DPROC,  TextureSubImage2D)
XMACRO(PFNGLBINDTEXTUREUNITPROC,    BindTextureUnit)

// -- target
// >= 3.0
//    XMACRO(PFNGLGENFRAMEBUFFERSPROC,      GenFramebuffers)
//    XMACRO(PFNGLFRAMEBUFFERTEXTURE2DPROC, FramebufferTexture2D)
XMACRO(PFNGLDELETEFRAMEBUFFERSPROC,  DeleteFramebuffers)
XMACRO(PFNGLDELETERENDERBUFFERSPROC, DeleteRenderbuffers)
// >= 4.5
XMACRO(PFNGLCREATEFRAMEBUFFERSPROC,           CreateFramebuffers)
XMACRO(PFNGLNAMEDFRAMEBUFFERTEXTUREPROC,      NamedFramebufferTexture)
XMACRO(PFNGLCREATERENDERBUFFERSPROC,          CreateRenderbuffers)
XMACRO(PFNGLNAMEDRENDERBUFFERSTORAGEPROC,     NamedRenderbufferStorage)
XMACRO(PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC, NamedFramebufferRenderbuffer)

// -- samplers
// >= 3.2
//    XMACRO(PFNGLGENSAMPLERSPROC,       GenSamplers)
//    XMACRO(PFNGLDELETESAMPLERSPROC,    DeleteSamplers)
//    XMACRO(PFNGLBINDSAMPLERPROC,       BindSampler)
//    XMACRO(PFNGLSAMPLERPARAMETERIPROC, SamplerParameteri)
// >= 4.5
//    XMACRO(PFNGLCREATESAMPLERSPROC, CreateSamplers)

// -- meshes
// >= 2.0
XMACRO(PFNGLGENBUFFERSPROC,               GenBuffers)
XMACRO(PFNGLDELETEBUFFERSPROC,            DeleteBuffers)
//    XMACRO(PFNGLBINDBUFFERPROC,               BindBuffer)
//    XMACRO(PFNGLBUFFERDATAPROC,               BufferData)
//    XMACRO(PFNGLDISABLEVERTEXATTRIBARRAYPROC, DisableVertexAttribArray)
//    XMACRO(PFNGLENABLEVERTEXATTRIBARRAYPROC,  EnableVertexAttribArray)
//    XMACRO(PFNGLVERTEXATTRIBPOINTERPROC,      VertexAttribPointer)
//    XMACRO(PFNGLBUFFERSUBDATAPROC,            BufferSubData)
// >= 3.0
//    XMACRO(PFNGLGENVERTEXARRAYSPROC,    GenVertexArrays)
XMACRO(PFNGLDELETEVERTEXARRAYSPROC, DeleteVertexArrays)
XMACRO(PFNGLBINDVERTEXARRAYPROC,    BindVertexArray)
// >= 4.3
//    XMACRO(PFNGLBINDVERTEXBUFFERPROC,    BindVertexBuffer)
//    XMACRO(PFNGLVERTEXATTRIBFORMATPROC,  VertexAttribFormat)
//    XMACRO(PFNGLVERTEXATTRIBBINDINGPROC, VertexAttribBinding)
// >= 4.5
XMACRO(PFNGLCREATEVERTEXARRAYSPROC,       CreateVertexArrays)
XMACRO(PFNGLCREATEBUFFERSPROC,            CreateBuffers)
XMACRO(PFNGLNAMEDBUFFERDATAPROC,          NamedBufferData)
XMACRO(PFNGLVERTEXARRAYELEMENTBUFFERPROC, VertexArrayElementBuffer)
XMACRO(PFNGLVERTEXARRAYVERTEXBUFFERPROC,  VertexArrayVertexBuffer)
//    XMACRO(PFNGLDISABLEVERTEXARRAYATTRIBPROC, DisableVertexArrayAttrib)
XMACRO(PFNGLENABLEVERTEXARRAYATTRIBPROC,  EnableVertexArrayAttrib)
XMACRO(PFNGLVERTEXARRAYATTRIBFORMATPROC,  VertexArrayAttribFormat)
XMACRO(PFNGLVERTEXARRAYATTRIBBINDINGPROC, VertexArrayAttribBinding)
XMACRO(PFNGLNAMEDBUFFERSTORAGEPROC,       NamedBufferStorage)
XMACRO(PFNGLNAMEDBUFFERSUBDATAPROC,       NamedBufferSubData)

// -- display
// >= 2.0
XMACRO(PFNGLVIEWPORTPROC,        Viewport)
XMACRO(PFNGLBINDFRAMEBUFFERPROC, BindFramebuffer)
//
XMACRO(PFNGLCLEARPROC,        Clear)
XMACRO(PFNGLDRAWELEMENTSPROC, DrawElements)
XMACRO(PFNGLDRAWARRAYSPROC,   DrawArrays)
XMACRO(PFNGLFINISHPROC,       Finish)
XMACRO(PFNGLFLUSHPROC,        Flush)

#undef XMACRO
