#if !defined(GAME_GRAPHICS_TYPES)
#define GAME_GRAPHICS_TYPES

enum Data_Type {
	DATA_TYPE_NONE,
	DATA_TYPE_UNIT,

	DATA_TYPE_U8,
	DATA_TYPE_U16,
	DATA_TYPE_U32,
	DATA_TYPE_U64,

	DATA_TYPE_S8,
	DATA_TYPE_S16,
	DATA_TYPE_S32,
	DATA_TYPE_S64,

	DATA_TYPE_R32,
	DATA_TYPE_R64,

	DATA_TYPE_VEC2,
	DATA_TYPE_VEC3,
	DATA_TYPE_VEC4,

	DATA_TYPE_MAT2,
	DATA_TYPE_MAT3,
	DATA_TYPE_MAT4,
};

enum Filter_Mode {
	FILTER_MODE_NONE,
	FILTER_MODE_POINT,
	FILTER_MODE_LERP,
};

enum Wrap_Mode {
	WRAP_MODE_REPEAT,
	WRAP_MODE_CLAMP,
};

enum Texture_Type {
	TEXTURE_TYPE_COLOR,
	TEXTURE_TYPE_DEPTH,
	TEXTURE_TYPE_STENCIL,
	TEXTURE_TYPE_DSTENCIL,
};

enum Mesh_Frequency {
	MESH_FREQUENCY_STATIC,
	MESH_FREQUENCY_DYNAMIC,
	MESH_FREQUENCY_STREAM,
};

enum Mesh_Access {
	MESH_ACCESS_DRAW,
	MESH_ACCESS_READ,
	MESH_ACCESS_COPY,
};

enum Comparison_Type {
	COMPARISON_TYPE_FALSE,
	COMPARISON_TYPE_TRUE,
	COMPARISON_TYPE_LESS,
	COMPARISON_TYPE_EQUAL,
	COMPARISON_TYPE_MORE,
	COMPARISON_TYPE_NOT_EQUAL,
	COMPARISON_TYPE_LESS_EQUAL,
	COMPARISON_TYPE_MORE_EQUAL,
};

enum Cull_Mode {
	CULL_MODE_BACK,
	CULL_MODE_FRONT,
	CULL_MODE_BOTH,
};

enum Winding_Order {
	WINDING_ORDER_NEGATIVE,
	WINDING_ORDER_POSITIVE,
};

enum Stencil_Op {
	STENCIL_OP_ZERO,
	STENCIL_OP_KEEP,
	STENCIL_OP_REPLACE,
	STENCIL_OP_INVERT,
	STENCIL_OP_INCR,
	STENCIL_OP_DECR,
	STENCIL_OP_INCR_WRAP,
	STENCIL_OP_DECR_WRAP,
};

enum Blend_Func {
	BLEND_FUNC_NONE,
	BLEND_FUNC_ADD,
	BLEND_FUNC_SUB,
	BLEND_FUNC_MIN,
	BLEND_FUNC_MAX,
	BLEND_FUNC_REVERSE_SUB,
};

enum Blend_Factor {
	BLEND_FACTOR_ZERO,
	BLEND_FACTOR_ONE,

	BLEND_FACTOR_SRC_COLOR,
	BLEND_FACTOR_SRC_ALPHA,
	BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
	BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,

	BLEND_FACTOR_DST_COLOR,
	BLEND_FACTOR_DST_ALPHA,
	BLEND_FACTOR_ONE_MINUS_DST_COLOR,
	BLEND_FACTOR_ONE_MINUS_DST_ALPHA,

	BLEND_FACTOR_CONST_COLOR,
	BLEND_FACTOR_CONST_ALPHA,
	BLEND_FACTOR_ONE_MINUS_CONST_COLOR,
	BLEND_FACTOR_ONE_MINUS_CONST_ALPHA,

	BLEND_FACTOR_SRC1_COLOR,
	BLEND_FACTOR_SRC1_ALPHA,
	BLEND_FACTOR_ONE_MINUS_SRC1_COLOR,
	BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA,
};

#endif
