#if !defined(GAME_GRAPHICS_TYPES)
#define GAME_GRAPHICS_TYPES

enum Data_Type {
	DATA_TYPE_NONE,
	DATA_TYPE_UNIT,
	DATA_TYPE_U8,
	DATA_TYPE_U16,
	DATA_TYPE_U32,
	DATA_TYPE_U64,
	DATA_TYPE_S8,
	DATA_TYPE_S16,
	DATA_TYPE_S32,
	DATA_TYPE_S64,
	DATA_TYPE_R32,
	DATA_TYPE_R64,
	DATA_TYPE_VEC2,
	DATA_TYPE_VEC3,
	DATA_TYPE_VEC4,
	DATA_TYPE_MAT2,
	DATA_TYPE_MAT3,
	DATA_TYPE_MAT4,
};

enum Filter_Mode {
	FILTER_MODE_NONE,
	FILTER_MODE_POINT,
	FILTER_MODE_LERP,
};

enum Wrap_Mode {
	WRAP_MODE_REPEAT,
	WRAP_MODE_CLAMP,
};

enum Texture_Type {
	TEXTURE_TYPE_COLOR,
	TEXTURE_TYPE_DEPTH,
	TEXTURE_TYPE_STENCIL,
	TEXTURE_TYPE_DSTENCIL,
};

#endif
